### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: ./misc/bilinear_warping.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE

### ISSUE THREAD

**Issue by XiaoLiang7** [D-Nilsson/GRFP#3]
Hi, I am running the master trunk and encounter the error when do training. Could anyone help on this? Thanks.

Traceback (most recent call last):
  File "train.py", line 12, in <module>
    bilinear_warping_module = tf.load_op_library('./misc/bilinear_warping.so')
  File "/home/liangxiao/anaconda3/envs/tf_1.3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: ./misc/bilinear_warping.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE

**Comment by D-Nilsson** [comment]
Hi,

Sorry for the (very) late reply. I missed this message. The error is probably due to using the wrong TensorFlow version. The code uses TensorFlow 1.4. If you switch to TensorFlow 1.4 (e.g. by running pip install tensorflow-gpu==1.4 in a virtualenv) it should work. It you want a newer TensorFlow version the compilation command was changed (see [here](https://www.tensorflow.org/extend/adding_an_op), 'GPU Support'). Try changing misc/compile.sh to the following:
````
TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )

nvcc -std=c++11 -c -o bilinear_warping.cu.o bilinear_warping.cu.cc \
  ${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

g++ -std=c++11 -shared -o bilinear_warping.so bilinear_warping.cc \
  bilinear_warping.cu.o ${TF_CFLAGS[@]} -fPIC -L /usr/local/cuda-9.0/lib64 -lcudart ${TF_LFLAGS[@]}
````
This worked for me with the latest TensorFlow version.

**Comment by yifanw90** [comment]
@D-Nilsson  Hi Dear, I follow your answer and change the cuda path. When  run 'sh compile.sh', I encountered :   compile.sh: 4: compile.sh: Bad substitution
with tensorflow-gpu 1.8  which is installed from the source code 
Waiting for your reply. 
Many thanks

**Comment by pdoublerainbow** [comment]
@yifanw90 Try to use tensorflow1.5.0.

**Comment by JanzYe** [comment]
@yifanw90 Hi, did you solve the problem? I tried to use tensorflow 1.4.1/1.5.0/1.14.0, all met the same problem. 

File "train.py", line 14, in <module>
    bilinear_warping_module = tf.load_op_library('./misc/bilinear_warping.so')
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./misc/bilinear_warping.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by wangchuan** [comment]
@JanzYe Yes, I encountered the same problem, with TensorFlow 1.14.0

**Comment by wufengbin123** [comment]
> @yifanw90 Try to use tensorflow1.5.0.

when I use tensorflow1.5.0 ，I compile successfully, but when I run evaluate.py ,I meet the probrom """TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'float64'> to <dtype: 'int32'> (Tensor is: <tf.Tensor 'flow/truediv_445:0' shape=() dtype=float64"""  ,I wonder if its due to the tensorflow version,  Did you run with 1.5.0 successfully without change network code?

**Comment by canyetat** [comment]
> 

hi,did you solve it? I meet this problem ,too.

**Comment by canyetat** [comment]
> .

hi,did you solve it? I meet this problem ,too.

**Comment by canyetat** [comment]
> > @yifanw90 Try to use tensorflow1.5.0.
> 
> when I use tensorflow1.5.0 ，I compile successfully, but when I run evaluate.py ,I meet the probrom """TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'float64'> to <dtype: 'int32'> (Tensor is: <tf.Tensor 'flow/truediv_445:0' shape=() dtype=float64""" ,I wonder if its due to the tensorflow version, Did you run with 1.5.0 successfully without change network code?

**Comment by canyetat** [comment]
> > @yifanw90 Try to use tensorflow1.5.0.
> 
> when I use tensorflow1.5.0 ，I compile successfully, but when I run evaluate.py ,I meet the probrom """TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'float64'> to <dtype: 'int32'> (Tensor is: <tf.Tensor 'flow/truediv_445:0' shape=() dtype=float64""" ,I wonder if its due to the tensorflow version, Did you run with 1.5.0 successfully without change network code?


hi,did you solve it? I meet this problem ,too.
